// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqnawjyahgjhsjlmxxhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxbmF3anlhaGdqaHNqbG14eGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTE5NjQsImV4cCI6MjA2OTE2Nzk2NH0.pqiSWCrPzt0I7LzmKIIPkQP-z2hSvMz7SuMPPImldxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});